import PDFDocument from 'pdfkit';
import { AggregatedReportData } from '@purrtrack/shared';

/**
 * Generates an executive Clockify-style PDF timesheet report.
 */
export async function generatePdfReport(data: AggregatedReportData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 40, size: 'A4' });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', (err) => reject(err));

      // Header Banner
      doc.rect(0, 0, 595.28, 60).fill('#5865F2'); // Discord Blurple
      doc.fillColor('#FFFFFF').fontSize(20).text('PurrTrack Time Report', 40, 20, { align: 'left' });
      doc.fontSize(10).text(data.guildName, 40, 42, { align: 'left' });

      doc.fillColor('#333333');
      doc.moveDown(3);

      // Period and metadata
      doc.fontSize(10).font('Helvetica-Bold').text('Reporting Period: ', { continued: true });
      doc.font('Helvetica').text(`${data.period.startDate.toLocaleDateString()} to ${data.period.endDate.toLocaleDateString()} (UTC)`);
      doc.moveDown(0.5);

      // KPI Metric Cards (3 boxes)
      const startY = doc.y;
      const boxWidth = 160;
      const boxHeight = 50;

      // Card 1: Total Duration
      doc.roundedRect(40, startY, boxWidth, boxHeight, 5).fillAndStroke('#F0F2F5', '#E4E6EB');
      doc.fillColor('#65676B').fontSize(8).font('Helvetica').text('TOTAL TIME TRACKED', 50, startY + 10);
      doc.fillColor('#1C1E21').fontSize(14).font('Helvetica-Bold').text(data.totalDurationFormatted, 50, startY + 24);

      // Card 2: Total Sessions
      doc.roundedRect(210, startY, boxWidth, boxHeight, 5).fillAndStroke('#F0F2F5', '#E4E6EB');
      doc.fillColor('#65676B').fontSize(8).font('Helvetica').text('TOTAL SESSIONS', 220, startY + 10);
      doc.fillColor('#1C1E21').fontSize(14).font('Helvetica-Bold').text(`${data.totalSessions}`, 220, startY + 24);

      // Card 3: Active Members
      doc.roundedRect(380, startY, boxWidth, boxHeight, 5).fillAndStroke('#F0F2F5', '#E4E6EB');
      doc.fillColor('#65676B').fontSize(8).font('Helvetica').text('ACTIVE MEMBERS', 390, startY + 10);
      doc.fillColor('#1C1E21').fontSize(14).font('Helvetica-Bold').text(`${data.uniqueActiveUsers}`, 390, startY + 24);

      doc.y = startY + boxHeight + 25;

      // Section: Session Details Table
      doc.fillColor('#1C1E21').fontSize(12).font('Helvetica-Bold').text('Voice Sessions Log');
      doc.moveDown(0.5);

      const tableTop = doc.y;
      const colUser = 40;
      const colChannel = 160;
      const colStart = 280;
      const colEnd = 380;
      const colDuration = 480;

      // Table Header
      doc.rect(40, tableTop, 515, 20).fill('#2B2D42');
      doc.fillColor('#FFFFFF').fontSize(8).font('Helvetica-Bold');
      doc.text('USER', colUser + 5, tableTop + 6);
      doc.text('CHANNEL', colChannel + 5, tableTop + 6);
      doc.text('START (UTC)', colStart + 5, tableTop + 6);
      doc.text('END (UTC)', colEnd + 5, tableTop + 6);
      doc.text('DURATION', colDuration + 5, tableTop + 6);

      let currentY = tableTop + 20;

      // Table Rows (limit to first 30 on PDF to keep layout neat)
      doc.font('Helvetica').fontSize(8).fillColor('#333333');

      for (let i = 0; i < Math.min(data.sessions.length, 30); i++) {
        const s = data.sessions[i];

        if (currentY > 750) {
          doc.addPage();
          currentY = 40;
        }

        if (i % 2 === 1) {
          doc.rect(40, currentY, 515, 18).fill('#F8F9FA');
          doc.fillColor('#333333');
        }

        const usernameText = s.displayName ? `${s.displayName} (@${s.username})` : s.username;
        doc.text(usernameText.substring(0, 20), colUser + 5, currentY + 5);
        doc.text(s.channelName.substring(0, 18), colChannel + 5, currentY + 5);
        doc.text(s.startedAt.toISOString().substring(11, 19), colStart + 5, currentY + 5);
        doc.text(s.endedAt.toISOString().substring(11, 19), colEnd + 5, currentY + 5);
        doc.text(s.durationFormatted, colDuration + 5, currentY + 5);

        currentY += 18;
      }

      if (data.sessions.length > 30) {
        doc.moveDown(1);
        doc.fontSize(8).font('Helvetica-Oblique').fillColor('#666666')
          .text(`* Displaying first 30 of ${data.sessions.length} sessions. For complete raw logs, export to Excel or CSV.`, 40, currentY + 10);
      }

      // Footer
      doc.fontSize(8).font('Helvetica').fillColor('#999999').text(
        `Generated by PurrTrack • ${new Date().toISOString()}`,
        40,
        800,
        { align: 'center', width: 515 }
      );

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}
